apiVersion: v1
kind: Service
metadata:
  name: contosoair-workflow
  namespace: namespace-workflow-1693903068443
spec:
  type: LoadBalancer
  selector:
    app: contosoair-workflow
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000