apiVersion: v1
kind: Service
metadata:
  name: contosoair10-cicd2
  namespace: namespace-workflow-1693843854779
spec:
  type: LoadBalancer
  selector:
    app: contosoair10-cicd2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000