apiVersion: v1
kind: Service
metadata:
  name: contosoair-deploy
  namespace: namespace-workflow-1693843705949
spec:
  type: LoadBalancer
  selector:
    app: contosoair-deploy
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000